# t-rex configuration for mvtbench

[service.mvt]
viewer = true

[[datasource]]
dbconn = "postgresql://hka@%2Frun%2Fpostgresql/mvtbench"
name = "pg"
default = true

[grid]
predefined = "web_mercator"

[[tileset]]
name = "ne_countries"
attribution = "Natural Earth v4"
extent = [-179.97277, -83.05457, 179.99366, 83.23559]

[[tileset.layer]]
name = "country"
geometry_field = "wkb_geometry"
geometry_type = "MULTIPOLYGON"
srid = 3857
buffer_size = 1
simplify = true
query_limit = 1000
[[tileset.layer.query]]
# ne_10m_admin_0_countries
minzoom = 0
maxzoom = 6
sql = """SELECT wkb_geometry, ogc_fid, featurecla, name, name_long, abbrev, adm0_a3_un AS adm0_a3, min_zoom, min_label, max_label FROM ne_10m_admin_0_countries WHERE min_zoom::integer <= !zoom! AND wkb_geometry && !bbox!"""
# ? "adm0_a3_is, adm0_a3_us, adm0_a3_un, adm0_a3_wb"
    # sql = "SELECT ST_AsBinary(wkb_geometry) AS geometry, ogc_fid, featurecla, name, name_long, abbrev, adm0_a3, min_zoom, min_label, max_label FROM ne_10m_admin_0_countries WHERE min_zoom <= !ZOOM! AND wkb_geometry && !BBOX!"

[[tileset.layer]]
name = "country-name"
geometry_field = "wkb_geometry"
geometry_type = "POINT"
fid_field = "ogc_fid"
srid = 3857
buffer_size = 0
[[tileset.layer.query]]
# ne_10m_admin_0_label_points
minzoom = 0
maxzoom = 6
sql = """SELECT wkb_geometry, ogc_fid, sr_subunit, scalerank FROM ne_10m_admin_0_label_points WHERE scalerank < !zoom! AND wkb_geometry && !bbox!"""

[[tileset.layer]]
name = "geo-lines"
geometry_field = "wkb_geometry"
geometry_type = "MULTILINESTRING"
srid = 3857
buffer_size = 0
simplify = true
query_limit = 1000
[[tileset.layer.query]]
# ne_10m_geographic_lines
minzoom = 0
maxzoom = 6
sql = """SELECT wkb_geometry, ogc_fid, name FROM ne_10m_geographic_lines WHERE wkb_geometry && !bbox!"""

[[tileset.layer]]
name = "land-border-country"
geometry_field = "wkb_geometry"
geometry_type = "MULTILINESTRING"
fid_field = "ogc_fid"
srid = 3857
buffer_size = 0
simplify = true
[[tileset.layer.query]]
# ne_10m_admin_0_boundary_lines_land
minzoom = 0
maxzoom = 6
sql = """SELECT wkb_geometry, ogc_fid, featurecla, name, min_zoom FROM ne_10m_admin_0_boundary_lines_land WHERE min_zoom::integer <= !zoom! AND wkb_geometry && !bbox!"""

[[tileset.layer]]
name = "state"
geometry_field = "wkb_geometry"
geometry_type = "MULTILINESTRING"
srid = 3857
buffer_size = 0
simplify = true
query_limit = 1000
[[tileset.layer.query]]
# ne_10m_admin_1_states_provinces_lines
minzoom = 0
maxzoom = 6
sql = """SELECT wkb_geometry, ogc_fid, featurecla, name, adm0_name, min_zoom, min_label FROM ne_10m_admin_1_states_provinces_lines WHERE min_zoom::integer <= !zoom! AND wkb_geometry && !bbox!"""

[cache.file]
base = "/tmp/mvtcache"
baseurl = "http://example.com/tiles"

[webserver]
# Bind address. Use 0.0.0.0 to listen on all adresses.
bind = "127.0.0.1"
port = 6767
#cache_control_max_age = 43200

[[webserver.static]]
path = "/map"
dir = "./map/"
